Repository VGandhi27/hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#1 created string folder
  String/CommonPrefix.java
  String/Palindrome_String.java
  String/Parenthesis_Checker.cpp
  String/Remove_all_duplicates.java
  String/Roman_Number_to_Integer.java
  String/Second_most_repeated_string_in_a_sequence.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#3 created array folder
  Array/Cyclically_rotate_an_array_by_one.java
  Array/First_and_last_occurrences_of_x.java
  Array/Kadane's_Algorithm.java
  Array/Palindromic_Array.java
  Array/Sort_an_array_of_0s_1s_and_2s.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#6 Create TrappingRainWater.java
  Array/TrappingRainWater.java
Labels: hacktoberfest, hacktoberfest-accepted

#7 Create Knapsack.java
  Dynamic Programming/Knapsack.java
Labels: hacktoberfest, hacktoberfest-accepted

#8 Create Check Anagram.java
  String/Check Anagram.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Added Rain Water Trapping Problem using Dynamic Programming
  Dynamic Programming/TrappingRainWater.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#10 Added Java code for Middle of LL
  LinkedList/LinkedListCycle.java
  LinkedList/middleOfLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#14 added new file in dp folder
  Dynamic Programming/ncr%p.java
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added binary search section and aggressive cows problem
  Binary Search/AggressiveCows.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 Java code for Peak Element in an array
  Array/MajorityElement.java
  Binary Search/peakElement.java
Labels: hacktoberfest, hacktoberfest-accepted

#18 Stack Data Structure added
  Stack/Stack_Implementation.c
  Stack/Stack_theory_application.txt
Labels: hacktoberfest, hacktoberfest-accepted

#28 adding 2D directory with a spiral matrix code in java
  2D Array/SpiralMatrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#23 Binary Tree Problems
  Binary Tree Problems/balanced.cpp
  Binary Tree Problems/diameter.cpp
  Binary Tree Problems/identical.cpp
  Binary Tree Problems/maxdepth.cpp
  Binary Tree Problems/maxwidth.cpp
  Binary Tree Problems/traversal.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 Create QS.java
  Array/QS.java
Labels: hacktoberfest, hacktoberfest-accepted

#26 read input string and integers, formats them, and prints the formatte…
  String/CheckAnagram.java
  String/OutputFormatting.java
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create Interval.java
  Array/Interval.java
Labels: hacktoberfest, hacktoberfest-accepted

#35 Add CRUD in C
  C CRUD/contoh_crud.c
  String/palindrome.c
Labels: hacktoberfest, hacktoberfest-accepted

#36 Create CycleDetectionPrt.java
  Dynamic Programming/CycleDetectionPrt.java
Labels: hacktoberfest, hacktoberfest-accepted

#38 Create ArrayCRUDOperation.java
  Array/ArrayCRUDOperation.java
Labels: hacktoberfest, hacktoberfest-accepted

#40 Algos added
  Graph/ShortestPathInDirectedAcyclic.cpp
  Graph/ShortestPathInUndirectedGraphs.cpp
  Graph/primsAlgo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#41 Created Dutch National Flag.cpp
  Array/Dutch National Flag.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 Created LONGEST INCREASING SUBSEQUENCE.CPP
  Dynamic Programming/LONGEST INCREASING SUBSEQUENCE.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#43 Merge_Two_Sorted_Linked_List
  LinkedList/Merge_Two_Sorted_List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#45 making change problem using java
  Dynamic Programming/making_change_problem.class
  Dynamic Programming/making_change_problem.java
Labels: hacktoberfest, hacktoberfest-accepted

#51 Duplicate elements identification in an array
  Array/Duplicate.java
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added Valid Parenthesis using Stack - JAVA
  Stack/ValidParenthesisUsingStack.java
Labels: hacktoberfest, hacktoberfest-accepted

#50 Create UniqueMinimumProductSubarra.java
  Array/UniqueMinimumProductSubarra.java
Labels: hacktoberfest, hacktoberfest-accepted

#52 Added Queue Folder
  Queue/BinaryNumbersUptoN.java
Labels: hacktoberfest, hacktoberfest-accepted

#53 ReverseLinkedList
  LinkedList/ReverseLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added Josephus Problem - QUEUE
  Queue/JosephusProblem.java
Labels: hacktoberfest, hacktoberfest-accepted

#55 Created Stack_Implementation.java
  Projects/Car Rental GUI/Available.java
  Projects/Car Rental GUI/README.md
  Projects/Car Rental GUI/Rent.java
  Projects/Car Rental GUI/Signup.java
  Projects/Car Rental GUI/Welcome.java
  Projects/Car Rental GUI/cars/Amaze.java
  Projects/Car Rental GUI/cars/Amaze.jpg
  Projects/Car Rental GUI/cars/Ertiga.java
  Projects/Car Rental GUI/cars/Ertiga.jpg
  Projects/Car Rental GUI/cars/Nexon.java
  Projects/Car Rental GUI/cars/Nexon.jpg
  Projects/Car Rental GUI/cars/Thar.java
  Projects/Car Rental GUI/cars/Thar.jpg
  Stack/Stack_Implementation.java
Labels: hacktoberfest, hacktoberfest-accepted

#57 I have added dijkstra_algorithm
  Graph/dijkstra_algorithm
Labels: hacktoberfest, hacktoberfest-accepted

#59 Spiral Traversal of Matrix
  Array/PrintSpirals.java
Labels: hacktoberfest, hacktoberfest-accepted

#61 Program to generate Pascal’s Triangle
  Array/PascalTriangle.java
Labels: hacktoberfest, hacktoberfest-accepted

#62 Merge Overlapping Sub-intervals
  Array/MergeOverlappingIntervals.java
Labels: hacktoberfest, hacktoberfest-accepted

#63 Maximum Product Subarray in an Array
  Array/SubarrayWithMaxProduct.java
Labels: hacktoberfest, hacktoberfest-accepted

#64 Added FibonacciGenerator.java
  FibonacciGenerator/FibonacciGenerator.java
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added MergeSort.java
  MergeSort/MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#66 Palindrome.py
  String/Pallindrome mystyle.py
Labels: hacktoberfest, hacktoberfest-accepted

#67 Create LinkedListSorting
  LinkedList/LinkedListSorting
Labels: hacktoberfest, hacktoberfest-accepted

#69 Program that solves Sudoku Puzzle
  Dynamic Programming/SudokuSolver.java
Labels: hacktoberfest, hacktoberfest-accepted

#68 Solution of Search in Rotated Sorted Array added
  Array/SearchInRotatedSortedArray.java
Labels: hacktoberfest, hacktoberfest-accepted

#73 Create Count Subsets with Sum K.cpp
  Dynamic Programming/Count Subsets with Sum K.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 to find Max_Element_In_Bitonic_Array
  Binary Search/MaxElementInBitonicArray.java
Labels: hacktoberfest, hacktoberfest-accepted

#70 NextGreaterElement.java
  Stack/NextGreaterElement.java
Labels: hacktoberfest, hacktoberfest-accepted

#71 added question on binary search
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Binary Search/pivot.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#79 Add Q First & Last Occurrence of an element
  Binary Search/First&LastOcc.java
Labels: hacktoberfest, hacktoberfest-accepted

#75 Create binary-search.cpp
  Binary Search/binary-search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#76 Create binary-search.java
  Binary Search/binary-search.java
Labels: hacktoberfest, hacktoberfest-accepted

#80 Added shell sort algorithm
  ShellSort/shell_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#85 Create ShellSort.java
  ShellSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#84 Added heapsort in java
  .vscode/launch.json
  HeapSort/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#81 Create flyod_warshall.cpp
  Graph/flyod_warshall.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#83 Create binary.py
  Binary Search/binary.py
Labels: hacktoberfest, hacktoberfest-accepted
